[extend]
useDefault = true

[[allowlists]]
description = "Ignore generated Next.js artifacts"
paths = [
  '''^self-checkout/\.next/.*'''
]

[[allowlists]]
description = "Allow SonarCloud public identifiers"
regexes = [
  '''joaopires3642''',
  '''JoaoPires3642_MKT-GUS'''
]
paths = [
  '''^\.github/workflows/ci\.yml$''',
  '''^sonar-project\.properties$'''
]
