sonar.organization=joaopires3642
sonar.projectKey=JoaoPires3642_MKT-GUS
sonar.projectName=MKT-GUS

sonar.sourceEncoding=UTF-8

sonar.sources=autoatendimento, self-checkout
sonar.tests=autoatendimento, self-checkout

sonar.test.inclusions=**/*Test.java,**/*.test.ts,**/*.test.tsx
sonar.exclusions=**/node_modules/**,**/.next/**,**/target/**,**/dist/**,**/coverage/**,**/.pnpm/**,**/*.min.js

sonar.java.binaries=autoatendimento/**/target/classes
sonar.javascript.lcov.reportPaths=self-checkout/coverage/lcov.info
